apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    isDefault: true
    url: timescaledb:5432
    user: grafana
    secureJsonData:
      password: grafana123
    jsonData:
      database: telemetry
      sslmode: 'disable'
      timescaledb: true
      postgresVersion: 1600
